import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import { Accessibility, ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, HeartHandshake, Home, LocateFixed, LockKeyhole, MapPin, Mic, Navigation, Pause, Phone, RotateCcw, ShieldCheck, Square, Trash2, UserRound, Volume2, X } from 'lucide-react'
import { journeyCopy, languages, screenLabels, uiCopy, type JourneyStep, type Locale, type ScreenId, type UiKey } from './data'
import exitPhoto from './assets/images/outram-exit-7.jpg'

type SpeechEvent = { results: ArrayLike<{ 0: { transcript: string } }> }
type Recognition = { lang:string; interimResults:boolean; continuous:boolean; onresult:((event:SpeechEvent)=>void)|null; onerror:(()=>void)|null; onend:(()=>void)|null; start:()=>void; stop:()=>void }
type LocationStatus = 'idle' | 'requesting' | 'active' | 'denied' | 'unavailable'
type Confirmation = { title:string; body:string; action:string; danger?:boolean; onConfirm:()=>void }
const storageKey = 'mdm-lim-locale'

function App() {
  const [screen,setScreen] = useState<ScreenId>('language')
  const [locale,setLocale] = useState<Locale>(()=>{const value=localStorage.getItem(storageKey);return value==='zh'||value==='ms'||value==='ta'?value:'en'})
  const [destination,setDestination] = useState('')
  const [activeStep,setActiveStep] = useState(0)
  const [sharing,setSharing] = useState(true)
  const [locationStatus,setLocationStatus] = useState<LocationStatus>('idle')
  const [lastLocationAt,setLastLocationAt] = useState<Date|null>(null)
  const [confirm,setConfirm] = useState<Confirmation|null>(null)
  const [helpMode,setHelpMode] = useState<'family'|'emergency'|'audio'>('family')
  const [helpDelivery,setHelpDelivery] = useState<'backend'|'prototype'>('prototype')
  const [sosReturn,setSosReturn] = useState<'guide'|'recovery'>('guide')
  const watchRef = useRef<number|null>(null)
  const c = uiCopy[locale]
  useEffect(()=>localStorage.setItem(storageKey,locale),[locale])
  useEffect(()=>()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current)},[])
  const navigate=(next:ScreenId)=>{setConfirm(null);setScreen(next)}
  const startJourney=()=>{
    if(!navigator.geolocation){setLocationStatus('unavailable');return}
    setLocationStatus('requesting')
    navigator.geolocation.getCurrentPosition(position=>{
      setLastLocationAt(new Date(position.timestamp));setLocationStatus('active');setActiveStep(0)
      if(sharing){watchRef.current=navigator.geolocation.watchPosition(next=>setLastLocationAt(new Date(next.timestamp)),()=>setLocationStatus('denied'),{enableHighAccuracy:true,maximumAge:15000})}
      navigate('guide')
    },()=>setLocationStatus('denied'),{enableHighAccuracy:true,timeout:6000})
  }
  const continueCached=()=>{setLocationStatus('denied');setSharing(false);setActiveStep(0);navigate('guide')}
  const finishJourney=()=>{if(watchRef.current!==null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}setSharing(false);setLocationStatus('idle');navigate('arrived')}
  const openSos=(origin:'guide'|'recovery')=>{setSosReturn(origin);navigate('sos')}
  const sendFamilyHelp=async()=>{
    let delivered:'backend'|'prototype'='prototype'
    const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),2200)
    try{
      const first=await fetch('http://127.0.0.1:8000/sos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:'mdm_lim'}),signal:controller.signal})
      if(first.ok){const body=await first.json() as {sos_id:string};const second=await fetch('http://127.0.0.1:8000/sos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:'mdm_lim',sos_id:body.sos_id,confirm:true}),signal:controller.signal});if(second.ok)delivered='backend'}
    }catch{delivered='prototype'}finally{window.clearTimeout(timeout)}
    setHelpDelivery(delivered);setHelpMode('family');navigate('help-sent')
  }
  const emergencyCall=()=>{setHelpMode('emergency');setHelpDelivery('prototype');navigate('help-sent');window.setTimeout(()=>{window.location.href='tel:995'},150)}
  return <main className="prototype-shell">
    <PrototypeNav screen={screen} locale={locale} activeStep={activeStep} navigate={navigate} setLocale={setLocale} setActiveStep={setActiveStep}/>
    <section className="device-stage" aria-label="Mdm Lim commuter companion"><div className="phone" lang={locale==='zh'?'zh':locale==='ms'?'ms':locale==='ta'?'ta':'en'}>
      {screen==='language'&&<LanguageScreen locale={locale} setLocale={setLocale} next={()=>navigate('profile')} c={c}/>}
      {screen==='profile'&&<ProfileScreen back={()=>navigate('language')} traveller={()=>navigate('plan')} family={()=>navigate('family')} c={c}/>}
      {screen==='plan'&&<PlanScreen destination={destination} setDestination={setDestination} back={()=>navigate('profile')} voice={()=>navigate('voice')} next={()=>navigate('overview')} c={c}/>}
      {screen==='voice'&&<VoiceScreen locale={locale} back={()=>navigate('plan')} accept={value=>{setDestination(value);navigate('overview')}} c={c}/>}
      {screen==='overview'&&<OverviewScreen locale={locale} back={()=>navigate('plan')} next={()=>navigate('sharing')} c={c}/>}
      {screen==='sharing'&&<SharingScreen sharing={sharing} setSharing={setSharing} locationStatus={locationStatus} back={()=>navigate('overview')} start={startJourney} cached={continueCached} c={c}/>}
      {screen==='guide'&&<GuideScreen locale={locale} stepIndex={activeStep} sharing={sharing} locationStatus={locationStatus} lastLocationAt={lastLocationAt} back={()=>navigate('overview')} next={()=>activeStep===7?finishJourney():setActiveStep(value=>Math.min(7,value+1))} help={()=>navigate('recovery')} sos={()=>openSos('guide')} c={c}/>}
      {screen==='recovery'&&<RecoveryScreen locale={locale} stepIndex={activeStep} back={()=>navigate('guide')} previous={()=>{setActiveStep(value=>Math.max(0,value-1));navigate('guide')}} contact={()=>openSos('recovery')} c={c}/>}
      {screen==='wrong-way'&&<WrongWayScreen back={()=>navigate('guide')} correct={()=>navigate('guide')} contact={()=>openSos('guide')} c={c}/>}
      {screen==='sos'&&<SosScreen back={()=>navigate(sosReturn)} record={()=>navigate('recording')} family={()=>setConfirm({title:c.trustedFamily,body:c.trustedDetail,action:c.trustedDetail,onConfirm:sendFamilyHelp})} emergency={()=>setConfirm({title:c.emergency,body:c.immediateDanger,action:'995',danger:true,onConfirm:emergencyCall})} c={c}/>}
      {screen==='recording'&&<RecordingScreen locale={locale} back={()=>navigate('sos')} sent={()=>{setHelpMode('audio');setHelpDelivery('prototype');navigate('help-sent')}} c={c}/>}
      {screen==='help-sent'&&<HelpSentScreen mode={helpMode} delivery={helpDelivery} back={()=>navigate('guide')} c={c}/>}
      {screen==='arrived'&&<ArrivedScreen done={()=>{setActiveStep(0);navigate('plan')}} c={c}/>}
      {screen==='family'&&<FamilyAccessScreen back={()=>navigate('profile')} next={()=>navigate('family-journey')} c={c}/>}
      {screen==='family-journey'&&<FamilyJourneyScreen locale={locale} activeStep={activeStep} sharing={sharing} locationStatus={locationStatus} back={()=>navigate('family')} c={c}/>}
      {confirm&&<ConfirmSheet {...confirm} close={()=>setConfirm(null)} cancel={c.cancel}/>}
    </div></section>
  </main>
}

function PrototypeNav({screen,locale,activeStep,navigate,setLocale,setActiveStep}:{screen:ScreenId;locale:Locale;activeStep:number;navigate:(s:ScreenId)=>void;setLocale:(l:Locale)=>void;setActiveStep:(n:number)=>void}){
  return <aside className="prototype-nav"><div className="prototype-brand"><span className="signal-mark"><i/><i/><i/></span><div><strong>Mdm Lim</strong><span>Commuter companion</span></div></div><p className="prototype-note">Presenter controls. Hidden on phones.</p><nav>{screenLabels.map((item,index)=><div key={item.id}>{item.group!==screenLabels[index-1]?.group&&<span className="nav-group">{item.group}</span>}<button className={screen===item.id?'active':''} onClick={()=>navigate(item.id)}><span>{item.label}</span><ChevronRight size={18}/></button></div>)}</nav><span className="nav-group">Live step</span><div className="nav-steps">{Array.from({length:8},(_,i)=><button key={i} className={screen==='guide'&&activeStep===i?'active':''} onClick={()=>{setActiveStep(i);navigate('guide')}}>{i+1}</button>)}</div><span className="nav-group">Demo language</span><div className="nav-language-buttons">{languages.map(item=><button key={item.id} className={locale===item.id?'active':''} onClick={()=>setLocale(item.id)}>{item.code}</button>)}</div></aside>
}

function BackButton({onClick,light=false,label='Go back'}:{onClick:()=>void;light?:boolean;label?:string}){return <button className={`back-button${light?' light':''}`} onClick={onClick} aria-label={label}><ArrowLeft/></button>}
function TopBar({title,back}:{title:string;back:()=>void}){return <header className="top-bar"><BackButton onClick={back}/><strong>{title}</strong><span/></header>}
function PrimaryButton({children,onClick,disabled=false}:{children:ReactNode;onClick?:()=>void;disabled?:boolean}){return <button className="primary-button" onClick={onClick} disabled={disabled}>{children}</button>}
function SecondaryButton({children,onClick}:{children:ReactNode;onClick?:()=>void}){return <button className="secondary-button" onClick={onClick}>{children}</button>}

function LanguageScreen({locale,setLocale,next,c}:{locale:Locale;setLocale:(l:Locale)=>void;next:()=>void;c:Record<UiKey,string>}){return <div className="screen language-screen"><section className="language-sheet"><p className="welcome">{c.welcome}</p><h1>{c.chooseLanguage}</h1><p className="helper">{c.canChange}</p><div className="language-list" role="radiogroup">{languages.map(item=><button key={item.id} className={locale===item.id?'selected':''} onClick={()=>setLocale(item.id)} role="radio" aria-checked={locale===item.id}><span>{item.label}</span><b>{item.code}</b></button>)}</div><PrimaryButton onClick={next}>{c.done}</PrimaryButton></section></div>}

function ProfileScreen({back,traveller,family,c}:{back:()=>void;traveller:()=>void;family:()=>void;c:Record<UiKey,string>}){return <div className="screen paper-screen profile-screen"><TopBar title={c.chooseProfile} back={back}/><h1>{c.whoUses}</h1><div className="role-list"><button onClick={traveller}><b>A</b><span><strong>{c.travelling}</strong><small>{c.travellingSub}</small></span><ArrowRight/></button><button onClick={family}><b>B</b><span><strong>{c.family}</strong><small>{c.familySub}</small></span><ArrowRight/></button></div><p className="consent-copy">{c.consent}</p></div>}

function PlaceField({label,value,placeholder,icon,onChange,voice}:{label:string;value:string;placeholder?:string;icon:ReactNode;onChange?:(v:string)=>void;voice:()=>void}){return <label className="place-field"><span>{label}</span><div>{icon}<input value={value} placeholder={placeholder} onChange={e=>onChange?.(e.target.value)} readOnly={!onChange}/><button onClick={voice} type="button" aria-label={label}><Mic/></button></div></label>}
function AccessibleStrip({c}:{c:Record<UiKey,string>}){return <div className="accessible-strip"><Accessibility/><span><strong>{c.accessibleOn}</strong><small>{c.accessibleSub}</small></span></div>}
function PlanScreen({destination,setDestination,back,voice,next,c}:{destination:string;setDestination:(v:string)=>void;back:()=>void;voice:()=>void;next:()=>void;c:Record<UiKey,string>}){
  const [error,setError]=useState('')
  const submit=()=>{if(!destination.trim()){setError(c.enterDestination);return}setError('');next()}
  return <div className="screen paper-screen plan-screen"><TopBar title={c.planTitle} back={back}/><section className="page-title"><h1>{c.whereGoing}</h1><p>{c.speakType}</p></section><div className="place-fields"><PlaceField label={c.from} value={c.homeBedok} icon={<Home/>} voice={voice}/><PlaceField label={c.to} value={destination} placeholder={c.enterPlace} icon={<MapPin/>} onChange={value=>{setDestination(value);setError('')}} voice={voice}/></div><AccessibleStrip c={c}/>{error&&<p className="form-error" role="alert">{error}</p>}<div className="screen-actions"><PrimaryButton onClick={submit}>{c.showJourney}</PrimaryButton></div></div>
}

function VoiceScreen({locale,back,accept,c}:{locale:Locale;back:()=>void;accept:(v:string)=>void;c:Record<UiKey,string>}){
  const [transcript,setTranscript]=useState('');const [state,setState]=useState<'requesting'|'listening'|'heard'|'unsupported'|'error'>('requesting');const ref=useRef<Recognition|null>(null)
  const listen=()=>{if(!ref.current)return;setTranscript('');setState('listening');try{ref.current.start()}catch{setState('error')}}
  useEffect(()=>{const scope=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const Ctor=scope.SpeechRecognition??scope.webkitSpeechRecognition;if(!Ctor){setState('unsupported');return}const recognition=new Ctor();recognition.lang=languages.find(item=>item.id===locale)?.speech??'en-SG';recognition.interimResults=false;recognition.continuous=false;recognition.onresult=e=>{const heard=e.results[0]?.[0]?.transcript??'';setTranscript(heard);setState(heard?'heard':'error')};recognition.onerror=()=>setState('error');recognition.onend=()=>setState(value=>value==='listening'?'error':value);ref.current=recognition;listenRecognition(recognition,setState);return()=>recognition.stop()},[locale])
  const demo=()=>{setTranscript('Singapore General Hospital');setState('heard')}
  return <div className="screen paper-screen listening-screen"><TopBar title={c.voiceTitle} back={back}/><section className="listening-title"><h1>{state==='listening'||state==='requesting'?c.listening:c.checkDestination}</h1><p>{state==='listening'||state==='requesting'?c.sayDestination:state==='unsupported'?c.micUnsupported:state==='error'?c.micDenied:c.noSpeechYet}</p></section><div className="capture-card"><button className={`big-mic${state==='listening'?' active':''}`} onClick={listen} disabled={state==='unsupported'}><Mic/></button><span>{transcript?c.heard:c.noSpeechYet}</span><strong>{transcript||'—'}</strong></div><div className="privacy-strip"><ShieldCheck/><span>{c.privacyMic}</span></div><div className="screen-actions voice-actions"><PrimaryButton onClick={()=>accept(transcript)} disabled={!transcript}>{c.useDestination}</PrimaryButton><SecondaryButton onClick={state==='unsupported'?demo:listen}>{state==='unsupported'?c.useDemo:c.tryAgain}</SecondaryButton><button className="plain-cancel" onClick={back}>{c.cancel}</button></div></div>
}
function listenRecognition(recognition:Recognition,setState:(v:'requesting'|'listening'|'heard'|'unsupported'|'error')=>void){try{recognition.start();setState('listening')}catch{setState('error')}}

function OverviewScreen({locale,back,next,c}:{locale:Locale;back:()=>void;next:()=>void;c:Record<UiKey,string>}){const steps=journeyCopy[locale];return <div className="screen paper-screen overview-screen"><TopBar title={c.journeyTitle} back={back}/><section className="overview-heading"><div><span>Bedok</span><ArrowRight/><span>SGH</span></div><h1>{c.simpleSteps}</h1><p>{c.duration}</p></section><div className="journey-badges"><span><Accessibility/>{c.stepFree}</span><span><LocateFixed/>{c.sheltered}</span></div><ol className="journey-list">{steps.map((step,index)=><li key={index} className={index===5?'featured':''}><b>{index+1}</b><span><strong>{step.title}</strong><small>{step.instruction}</small></span></li>)}</ol><div className="screen-actions"><PrimaryButton onClick={next}>{c.startJourney}</PrimaryButton></div></div>}

function SharingScreen({sharing,setSharing,locationStatus,back,start,c,cached}:{sharing:boolean;setSharing:(v:boolean)=>void;locationStatus:LocationStatus;back:()=>void;start:()=>void;cached:()=>void;c:Record<UiKey,string>}){return <div className="screen paper-screen sharing-screen"><TopBar title={c.shareTitle} back={back}/><section className="sharing-intro"><span><HeartHandshake/></span><h1>{c.shareHeading}</h1><p>{c.shareBody}</p></section><button className={`sharing-choice${sharing?' selected':''}`} onClick={()=>setSharing(!sharing)} role="switch" aria-checked={sharing}><span><UserRound/></span><span><strong>{c.shareWith}</strong><small>{sharing?c.shareOn:c.shareOff}</small></span><b>{sharing?<Check/>:null}</b></button><div className="location-explainer"><LocateFixed/><p>{c.locationExplain}</p></div>{locationStatus==='requesting'&&<p className="status-message" role="status">{c.requestingLocation}</p>}{(locationStatus==='denied'||locationStatus==='unavailable')&&<p className="status-message error" role="alert">{c.locationDenied}</p>}<div className="screen-actions two"><PrimaryButton onClick={start} disabled={locationStatus==='requesting'}><LocateFixed/>{c.allowStart}</PrimaryButton>{(locationStatus==='denied'||locationStatus==='unavailable')&&<SecondaryButton onClick={cached}>{c.continueCached}</SecondaryButton>}</div></div>}

function speakStep(step:JourneyStep,locale:Locale,onEnd?:()=>void){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(`${step.title}. ${step.instruction}. ${step.distance}.`);u.lang=languages.find(item=>item.id===locale)?.speech??'en-SG';u.rate=.72;u.onend=()=>onEnd?.();u.onerror=()=>onEnd?.();speechSynthesis.cancel();speechSynthesis.speak(u)}
function JourneyStatus({sharing,locationStatus,c}:{sharing:boolean;locationStatus:LocationStatus;c:Record<UiKey,string>}){return <div className="journey-status"><span><LocateFixed/>{locationStatus==='active'?c.locationOn:c.cachedDirections}</span><span><HeartHandshake/>{sharing?c.sharedWith:c.notShared}</span>{sharing&&<em>{c.demoSharing}</em>}</div>}
function GuideScreen({locale,stepIndex,sharing,locationStatus,lastLocationAt,back,next,help,sos,c}:{locale:Locale;stepIndex:number;sharing:boolean;locationStatus:LocationStatus;lastLocationAt:Date|null;back:()=>void;next:()=>void;help:()=>void;sos:()=>void;c:Record<UiKey,string>}){
  const step=journeyCopy[locale][stepIndex];const [speaking,setSpeaking]=useState(false);const play=()=>{if(speaking){speechSynthesis.cancel();setSpeaking(false)}else{setSpeaking(true);speakStep(step,locale,()=>setSpeaking(false))}}
  const controls=<><JourneyStatus sharing={sharing} locationStatus={locationStatus} c={c}/><div className="live-actions"><button onClick={play}>{speaking?<Pause/>:<Volume2/>}<span>{speaking?c.playing:c.playInstruction}</span></button><button onClick={help}><CircleHelp/><span>{c.needHelp}</span></button></div><PrimaryButton onClick={next}>{stepIndex===7?c.arrivedAction:c.nextStep}<ArrowRight/></PrimaryButton></>
  if(stepIndex===5)return <div className={`screen guide-screen locale-${locale}`}><img src={exitPhoto} alt="Illuminated yellow Exit 7 sign at Outram Park MRT" className="guide-photo"/><div className="photo-shade"/><div className="guide-top simple"><BackButton onClick={back} light/><strong>{step.place}</strong><span/></div><button className="floating-sos" onClick={sos}>SOS</button><section className="guide-sheet journey-guide-sheet"><div className="progress-row"><strong>{stepIndex+1} / 8</strong><span style={{'--progress':`${((stepIndex+1)/8)*100}%`} as CSSProperties}><i/></span></div><h1>{step.title}</h1><p className="instruction">{step.instruction}</p><div className="distance"><strong>{step.distance}</strong></div>{controls}</section></div>
  return <div className={`screen paper-screen standard-guide locale-${locale}`}><TopBar title={step.place} back={back}/><button className="floating-sos standard" onClick={sos}>SOS</button><section className="standard-visual"><Navigation/><span>{stepIndex+1}</span></section><section className="standard-sheet"><div className="progress-row"><strong>{stepIndex+1} / 8</strong><span style={{'--progress':`${((stepIndex+1)/8)*100}%`} as CSSProperties}><i/></span></div><h1>{step.title}</h1><p>{step.instruction}</p><div className="standard-distance">{step.distance}</div>{lastLocationAt&&<small>{lastLocationAt.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>}{controls}</section></div>
}

function RecoveryScreen({locale,stepIndex,back,previous,contact,c}:{locale:Locale;stepIndex:number;back:()=>void;previous:()=>void;contact:()=>void;c:Record<UiKey,string>}){const step=journeyCopy[locale][stepIndex];return <div className="screen paper-screen recovery-screen"><TopBar title={c.recoveryTitle} back={back}/><section className="recovery-intro"><span><CircleHelp/></span><h1>{c.recoveryHeading}</h1><p>{c.recoveryBody}</p></section><div className="recovery-options"><button onClick={()=>speakStep(step,locale)}><Volume2/><span>{c.repeatInstruction}</span><ChevronRight/></button><button onClick={back}><Navigation/><span>{c.showLandmark}</span><ChevronRight/></button><button onClick={back}><LocateFixed/><span>{c.checkLocation}</span><ChevronRight/></button>{stepIndex>0&&<button onClick={previous}><ArrowLeft/><span>{c.previousStep}</span><ChevronRight/></button>}<button onClick={contact}><HeartHandshake/><span>{c.contactFamily}</span><ChevronRight/></button></div><button className="emergency-link" onClick={contact}>{c.emergencySos}</button></div>}

function WrongWayScreen({back,correct,contact,c}:{back:()=>void;correct:()=>void;contact:()=>void;c:Record<UiKey,string>}){return <div className="screen wrong-screen"><div className="warning-top"><BackButton onClick={back}/><strong>{c.wrongTitle}</strong><span className="simulation-badge">{c.simulated}</span></div><RotateCcw className="turn-symbol"/><section className="wrong-sheet"><h1>{c.wrongHeading}</h1><p>{c.wrongBody}</p><div className="screen-actions two"><PrimaryButton onClick={correct}>{c.correctDirection}</PrimaryButton><SecondaryButton onClick={contact}>{c.callFamily}</SecondaryButton></div></section></div>}

function HelpOption({icon,title,detail,onClick}:{icon:ReactNode;title:string;detail:string;onClick:()=>void}){return <button className="help-option" onClick={onClick}><span>{icon}</span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight/></button>}
function SosScreen({back,record,family,emergency,c}:{back:()=>void;record:()=>void;family:()=>void;emergency:()=>void;c:Record<UiKey,string>}){return <div className="screen paper-screen sos-screen"><header className="simple-header"><BackButton onClick={back}/><strong>{c.getHelp}</strong></header><span className="sos-mark">SOS</span><section className="sos-title"><h1>{c.whoCall}</h1><p>{c.noCall}</p></section><div className="help-options"><HelpOption icon={<UserRound/>} title={c.trustedFamily} detail={c.trustedDetail} onClick={family}/><HelpOption icon={<Phone/>} title={c.emergency} detail={c.immediateDanger} onClick={emergency}/><HelpOption icon={<Mic/>} title={c.recordAudio} detail={c.optionalRecording} onClick={record}/></div><p className="privacy-footer"><Check/>{c.privacyFooter}</p></div>}

function RecordingScreen({locale,back,sent,c}:{locale:Locale;back:()=>void;sent:()=>void;c:Record<UiKey,string>}){const [recording,setRecording]=useState(false);const [seconds,setSeconds]=useState(0);const [audioUrl,setAudioUrl]=useState('');const [error,setError]=useState('');const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);useEffect(()=>{if(!recording)return;const timer=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(timer)},[recording]);useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const next=new MediaRecorder(stream);chunks.current=[];next.ondataavailable=e=>chunks.current.push(e.data);next.onstop=()=>{setAudioUrl(URL.createObjectURL(new Blob(chunks.current,{type:next.mimeType})));stream.getTracks().forEach(track=>track.stop())};next.start();recorder.current=next;setSeconds(0);setRecording(true);setError('')}catch{setError(c.micDenied)}};const stop=()=>{recorder.current?.stop();setRecording(false)};const clear=()=>{if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl('');setSeconds(0)};return <div className={`screen paper-screen recording-screen locale-${locale}`}><TopBar title={c.recordingTitle} back={back}/><section><span className={`recording-orb${recording?' active':''}`}>{recording?<Square/>:<Mic/>}</span><h1>{recording?c.recording:audioUrl?c.messageReady:c.recordShort}</h1><p>{recording?c.recordPrompt:c.nothingShared}</p><strong className="recording-time">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></section>{error&&<p className="recording-error">{error}</p>}{audioUrl&&<audio className="audio-player" controls src={audioUrl}/>}<div className="screen-actions two">{recording?<PrimaryButton onClick={stop}><Square/>{c.stopRecording}</PrimaryButton>:!audioUrl?<PrimaryButton onClick={start}><Mic/>{c.startRecording}</PrimaryButton>:<><PrimaryButton onClick={sent}>{c.confirmMessage}</PrimaryButton><SecondaryButton onClick={clear}><Trash2/>{c.deleteTry}</SecondaryButton></>}</div></div>}

function HelpSentScreen({mode,delivery,back,c}:{mode:'family'|'emergency'|'audio';delivery:'backend'|'prototype';back:()=>void;c:Record<UiKey,string>}){return <div className="screen paper-screen outcome-screen"><TopBar title={c.getHelp} back={back}/><section><span><Check/></span><h1>{c.helpSent}</h1><p>{mode==='family'?c.helpSentBody:mode==='audio'?c.nothingShared:c.immediateDanger}</p><div className="outcome-detail"><ShieldCheck/><strong>{delivery==='backend'?c.helpSentBody:c.backendNote}</strong></div></section><div className="screen-actions"><PrimaryButton onClick={back}>{c.backJourney}</PrimaryButton></div></div>}
function ArrivedScreen({done,c}:{done:()=>void;c:Record<UiKey,string>}){return <div className="screen paper-screen arrived-screen"><section><span><Check/></span><h1>{c.arrivedHeading}</h1><p>{c.arrivedBody}</p><div><ShieldCheck/>{c.sharingStopped}</div></section><div className="screen-actions"><PrimaryButton onClick={done}>{c.done}</PrimaryButton></div></div>}

function FamilyAccessScreen({back,next,c}:{back:()=>void;next:()=>void;c:Record<UiKey,string>}){const [code,setCode]=useState('');return <div className="screen paper-screen family-screen"><TopBar title={c.familyAccess} back={back}/><section className="family-intro"><span><HeartHandshake/></span><h1>{c.followShared}</h1><p>{c.shareConsent}</p></section><label className="code-field"><span>{c.sharingCode}</span><input value={code} placeholder="LIM-7284" onChange={e=>setCode(e.target.value.toUpperCase())}/></label><div className="family-consent"><LockKeyhole/><span><strong>{c.consentFirst}</strong><small>{c.sharingEnds}</small></span></div><div className="screen-actions"><PrimaryButton onClick={next}>{c.openDemo}</PrimaryButton></div></div>}
function FamilyJourneyScreen({locale,activeStep,sharing,locationStatus,back,c}:{locale:Locale;activeStep:number;sharing:boolean;locationStatus:LocationStatus;back:()=>void;c:Record<UiKey,string>}){const step=journeyCopy[locale][activeStep];return <div className="screen paper-screen family-journey"><TopBar title={c.familyJourney} back={back}/><section className="family-status"><span className="live-dot"><i/>{c.journeyActive}</span><h1>{c.onWay}</h1><p>{c.updatedNow}</p></section><div className="current-step"><span>{activeStep+1}</span><div><small>{c.currentStep}</small><strong>{step.title}</strong><p>{step.place}</p></div></div><dl><div><dt>{c.expectedArrival}</dt><dd>24 min</dd></div><div><dt>{c.direction}</dt><dd className="positive"><Check/>{c.rightPath}</dd></div><div><dt>{c.sharing}</dt><dd>{sharing&&locationStatus==='active'?c.untilEnds:c.notShared}</dd></div></dl><div className="family-note"><ShieldCheck/><span>{c.noHelp}</span></div><div className="screen-actions"><SecondaryButton onClick={back}>{c.stopViewing}</SecondaryButton></div></div>}

function ConfirmSheet({title,body,action,danger,onConfirm,close,cancel}:{title:string;body:string;action:string;danger?:boolean;onConfirm:()=>void;close:()=>void;cancel:string}){return <div className="modal" role="dialog" aria-modal="true"><button className="modal-backdrop" onClick={close}/><section><button className="modal-close" onClick={close}><X/></button><span className="modal-icon"><Phone/></span><h2>{title}</h2><p>{body}</p><button className={danger?'danger-button':'primary-button'} onClick={()=>{close();onConfirm()}}>{action}</button><SecondaryButton onClick={close}>{cancel}</SecondaryButton></section></div>}

export default App
