import type { Locale } from './data'

const en = {
  back: 'Go back', cancel: 'Cancel', language: { welcome: 'Welcome!', title: 'Choose your language.', helper: 'You can change this later.', continue: 'Continue', aria: 'Choose your language' },
  profile: { top: 'Choose your profile', title: 'Who is using this app?', traveller: 'I am travelling', travellerDetail: 'Plan and follow my own journey.', family: 'I am family', familyDetail: 'Follow journeys that are shared with me.', consent: 'Location is shared only when you choose.' },
  setup: { top: 'About your journey needs', title: 'A few questions so routes fit you', shelter: 'Do you prefer sheltered routes?', shelterYes: 'Yes, keep me under cover', shelterNo: 'No preference', stairs: 'Can you use stairs?', stairsAvoid: 'I avoid stairs', stairsOk: 'Stairs are fine', wheelchair: 'Do you use a wheelchair?', wcYes: 'Yes', wcNo: 'No', pace: 'How do you walk?', paceSlow: 'I walk slowly', paceAvg: 'I walk at an average pace', walk: 'How far can you comfortably walk?', metres: (m: number) => `${m} m`, save: 'Save and continue', saving: 'Saving…', failed: 'Could not save your profile. Try again.' },
  plan: { top: 'Plan a journey', title: 'Where are you going?', helper: 'Speak or type a place.', from: 'From', to: 'To', home: 'Home in Bedok', placeholder: 'Enter a place', planning: 'Planning…', show: 'Show my journey', uncovered: 'That place is not covered yet.', corridor: 'This prototype currently supports:', try: 'Try this route' },
  voice: { top: 'Voice destination', say: 'Say your destination', listening: 'Listening…', check: 'Check the destination', idle: 'Tap the microphone, then speak.', requesting: 'Waiting for microphone permission…', live: 'Speak now.', denied: 'Microphone access is off. Allow it in browser settings, or type instead.', unsupported: 'Voice input is unavailable here. Type your destination instead.', noSpeech: 'Nothing was heard. Try again or type instead.', error: 'Voice input could not start. Try again or type instead.', confirm: 'Is this the correct destination?', heard: 'I heard:', micLive: 'Microphone is on', nothing: 'Nothing heard yet', privacy: 'The microphone starts only after you tap and stops when listening ends.', use: 'Use this destination', tap: 'Tap to speak', retry: 'Try again', type: 'Type destination instead' },
  overview: { top: 'Your journey', title: (steps: number) => steps === 1 ? '1 step' : `${steps} steps`, about: (minutes: number) => `About ${minutes} minutes at your walking pace.`, stepFree: 'Step-free route', landmarks: 'Landmark guidance', start: 'Start journey', planning: 'Planning your journey…', checking: 'Checking current conditions.', empty: 'No journey yet', emptyDetail: 'Plan a journey first.', why: 'Why this route changed', simulated: 'Simulated disruption for demonstration' },
  stages: { title: 'Demo: one journey, three events', s1: 'Stage 1 · Peak-hour crowds', s2: 'Stage 2 · Planned closure', s3: 'Stage 3 · Train fault ahead' },
  legs: { modes: { walk: 'Walk', mrt: 'MRT', bus: 'Bus', taxi: 'Taxi' }, stepFree: { verified: 'Step-free', unverified: 'Step-free not verified', not_step_free: 'Not step-free' }, crowd: { low: 'Crowd: low', medium: 'Crowd: medium', high: 'Crowd: high' }, illustrative: 'Landmark photo — illustrative' },
  sharing: { top: 'Journey sharing', title: 'Share this journey with Hui Ling?', idle: 'Hui Ling can see your current step and last known location until you arrive.', requesting: 'Waiting for location permission…', denied: 'Location access is off. Enable it in browser settings, then try again.', timeout: 'We could not find your location. Try again somewhere with a clearer signal.', service: 'Your location could not be shared with Hui Ling. Try again.', unavailable: 'Location sharing is unavailable in this browser.', location: 'Current location', locationDetail: 'Shared only during this journey', control: 'You stay in control', controlDetail: 'Sharing stops when the journey ends', request: 'Requesting permission…', retry: 'Try location again', start: 'Share location and start', skip: 'Start without sharing' },
  guide: { step: (step: number, total: number) => `Step ${step} of ${total}`, sharing: 'Sharing with Hui Ling', saved: 'Using saved directions', updated: (time: string) => `Updated ${time}`, notShared: 'Location is not being shared', playing: 'Playing…', play: 'Play instruction', help: 'Need help?', finish: 'Finish journey', next: 'Next step' },
  help: { top: 'Check your direction', checking: 'Checking your direction…', lost: 'Need help finding the way?', wrong: 'Stop and turn around', wrongBody: 'You are walking away from the route.', familyTold: 'Hui Ling has been notified.', safe: 'You are still on your planned route.', unavailable: 'We could not check your direction. Use the buttons below.', noJourney: 'Plan a journey first.', correct: 'Show my direction', call: 'Contact Hui Ling' },
  taxi: { show: 'Show this card to the driver', arriveBy: 'Arrive by' },
  alert: { band: 'Travel alert', happened: { train: 'Train stopped ahead', flood: 'Flash flooding on your route', lift: 'A lift is out of service', weather: 'Heavy rain on your route', crowd: 'Severe crowding ahead', default: 'Conditions on your route changed' }, getOff: (p: string) => `Get off at ${p}`, goTo: (p: string) => `Go to ${p}`, stay: 'Do not start this journey', taxiTo: (d: string) => `Take a taxi to ${d}`, cancel: 'Travel another day', exit: { yes: (r: string) => `Exit ${r}: step-free (OSM)`, no: (r: string) => `Exit ${r}: OSM says not wheelchair-accessible`, untagged: (r: string) => `Exit ${r} (access not tagged in OSM)` }, stand: (n: string, m: number) => `Taxi stand: ${n}, about ${Math.round(m / 10) * 10} m`, cta: 'Show me the way', ok: 'Back to my journey', why: 'Why?' },
  arrived: { title: 'You have arrived', detail: 'Journey complete. Well done.', again: 'Plan a new journey' },
  sos: { top: 'Get help', title: 'Who should we contact?', idle: 'No call, message or recording has started.', family: 'Hui Ling', familyDetail: 'Send your current step and last known location', emergency: 'Emergency services', emergencyDetail: 'Call 995 for immediate danger', record: 'Record an audio message', recordDetail: 'Optional; never starts automatically', privacy: 'Audio and location are shared only after confirmation.', sendTitle: 'Send a help request to Hui Ling?', sendBody: 'She will receive your current step and last known location. Nothing is sent until you confirm.', send: 'Send help request', emergencyTitle: 'Call emergency services?', emergencyBody: 'Call 995 only for an immediate emergency.' },
}

export type UiCopy = typeof en

const zh: UiCopy = {
  back: '返回', cancel: '取消', language: { welcome: '欢迎！', title: '请选择您的语言。', helper: '您以后可以更改语言。', continue: '继续', aria: '选择语言' },
  profile: { top: '选择个人资料', title: '谁在使用此应用？', traveller: '我要出行', travellerDetail: '规划并跟随自己的行程。', family: '我是家人', familyDetail: '查看与我分享的行程。', consent: '只有在您选择时才会分享位置。' },
  setup: { top: '您的出行需求', title: '几个问题，让路线更适合您', shelter: '您偏好有遮盖的路线吗？', shelterYes: '是，尽量有遮盖', shelterNo: '无偏好', stairs: '您能使用楼梯吗？', stairsAvoid: '我避免楼梯', stairsOk: '楼梯没问题', wheelchair: '您使用轮椅吗？', wcYes: '是', wcNo: '否', pace: '您的步行速度如何？', paceSlow: '我走得比较慢', paceAvg: '我以一般速度行走', walk: '您能舒适地走多远？', metres: (m) => `${m} 米`, save: '保存并继续', saving: '保存中…', failed: '无法保存资料。请重试。' },
  plan: { top: '规划行程', title: '您要去哪里？', helper: '说出或输入地点。', from: '出发地', to: '目的地', home: '勿洛的家', placeholder: '输入地点', planning: '正在规划…', show: '显示我的行程', uncovered: '这个地点暂不支持。', corridor: '此原型目前支持：', try: '尝试此路线' },
  voice: { top: '语音目的地', say: '说出您的目的地', listening: '正在聆听…', check: '检查目的地', idle: '点击麦克风，然后说话。', requesting: '正在等待麦克风权限…', live: '请说话。', denied: '麦克风权限已关闭。请在浏览器设置中允许，或改用输入。', unsupported: '此处无法使用语音输入。请改用输入。', noSpeech: '没有听到声音。请重试或改用输入。', error: '无法启动语音输入。请重试或改用输入。', confirm: '这是正确的目的地吗？', heard: '我听到：', micLive: '麦克风已开启', nothing: '尚未听到内容', privacy: '麦克风只会在您点击后启动，并在聆听结束时停止。', use: '使用此目的地', tap: '点击说话', retry: '重试', type: '改用文字输入' },
  overview: { top: '您的行程', title: (steps) => `${steps} 个步骤`, about: (minutes) => `按您的步行速度，约 ${minutes} 分钟。`, stepFree: '无阶梯路线', landmarks: '地标指引', start: '开始行程', planning: '正在规划行程…', checking: '正在检查当前情况。', empty: '尚无行程', emptyDetail: '请先规划行程。', why: '为什么路线有变化', simulated: '演示用模拟中断' },
  stages: { title: '演示：一次行程，三个事件', s1: '第一幕 · 高峰人潮', s2: '第二幕 · 计划关闭', s3: '第三幕 · 前方列车故障' },
  legs: { modes: { walk: '步行', mrt: '地铁', bus: '巴士', taxi: '德士' }, stepFree: { verified: '无阶梯', unverified: '无阶梯状态未核实', not_step_free: '有阶梯' }, crowd: { low: '人流：少', medium: '人流：中', high: '人流：多' }, illustrative: '地标照片，仅供参考' },
  sharing: { top: '行程分享', title: '与慧玲分享此行程？', idle: '慧玲可在您抵达前查看当前步骤和最后位置。', requesting: '正在等待位置权限…', denied: '位置权限已关闭。请在浏览器设置中启用后重试。', timeout: '无法找到您的位置。请到信号较好的地方重试。', service: '无法与慧玲分享位置。请重试。', unavailable: '此浏览器无法使用位置分享。', location: '当前位置', locationDetail: '只在本次行程中分享', control: '由您决定', controlDetail: '行程结束后停止分享', request: '正在请求权限…', retry: '重新尝试位置', start: '分享位置并开始', skip: '不分享位置并开始' },
  guide: { step: (step, total) => `第 ${step} 步，共 ${total} 步`, sharing: '正在与慧玲分享', saved: '使用已保存的路线', updated: (time) => `${time} 已更新`, notShared: '未分享位置', playing: '正在播放…', play: '播放语音指示', help: '需要帮助？', finish: '完成行程', next: '下一步' },
  help: { top: '检查方向', checking: '正在检查方向…', lost: '需要帮助找路吗？', wrong: '停下并转身', wrongBody: '您正走离规划路线。', familyTold: '已通知慧玲。', safe: '您仍在规划路线中。', unavailable: '无法检查方向。请使用下方按钮。', noJourney: '请先规划行程。', correct: '显示我的方向', call: '联系慧玲' },
  taxi: { show: '请向司机出示此卡', arriveBy: '抵达时间' },
  alert: { band: '出行警报', happened: { train: '前方列车停驶', flood: '路线上发生淹水', lift: '有电梯停用', weather: '路线上有大雨', crowd: '前方严重拥挤', default: '路线情况有变' }, getOff: (p) => `请在${p}下车`, goTo: (p) => `请前往${p}`, stay: '请不要开始此行程', taxiTo: (d) => `乘德士前往${d}`, cancel: '请改天出行', exit: { yes: (r) => `${r} 出口：无障碍（OSM）`, no: (r) => `${r} 出口：OSM 标注不适合轮椅`, untagged: (r) => `${r} 出口（OSM 未标注通行情况）` }, stand: (n, m) => `德士站：${n}，约 ${Math.round(m / 10) * 10} 米`, cta: '为我指路', ok: '返回行程', why: '为什么？' },
  arrived: { title: '您已抵达', detail: '行程完成。辛苦了。', again: '规划新行程' },
  sos: { top: '寻求帮助', title: '我们应该联系谁？', idle: '尚未开始通话、信息或录音。', family: '慧玲', familyDetail: '发送当前步骤和最后位置', emergency: '紧急服务', emergencyDetail: '如有紧急危险，请拨打 995', record: '录制语音信息', recordDetail: '可选；不会自动开始', privacy: '音频和位置只会在确认后分享。', sendTitle: '向慧玲发送求助信息？', sendBody: '她会收到您当前的步骤和最后位置。确认前不会发送。', send: '发送求助信息', emergencyTitle: '拨打紧急服务？', emergencyBody: '只有在紧急危险时才拨打 995。' },
}

const ms: UiCopy = {
  back: 'Kembali', cancel: 'Batal', language: { welcome: 'Selamat datang!', title: 'Pilih bahasa anda.', helper: 'Anda boleh menukarnya kemudian.', continue: 'Teruskan', aria: 'Pilih bahasa' },
  profile: { top: 'Pilih profil anda', title: 'Siapa yang menggunakan aplikasi ini?', traveller: 'Saya sedang dalam perjalanan', travellerDetail: 'Rancang dan ikuti perjalanan saya.', family: 'Saya ahli keluarga', familyDetail: 'Ikuti perjalanan yang dikongsi dengan saya.', consent: 'Lokasi dikongsi hanya apabila anda memilihnya.' },
  setup: { top: 'Keperluan perjalanan anda', title: 'Beberapa soalan supaya laluan sesuai untuk anda', shelter: 'Adakah anda suka laluan berbumbung?', shelterYes: 'Ya, utamakan berbumbung', shelterNo: 'Tiada keutamaan', stairs: 'Bolehkah anda menggunakan tangga?', stairsAvoid: 'Saya elak tangga', stairsOk: 'Tangga tiada masalah', wheelchair: 'Adakah anda menggunakan kerusi roda?', wcYes: 'Ya', wcNo: 'Tidak', pace: 'Bagaimana anda berjalan?', paceSlow: 'Saya berjalan perlahan', paceAvg: 'Saya berjalan pada kelajuan biasa', walk: 'Sejauh mana anda selesa berjalan?', metres: (m) => `${m} m`, save: 'Simpan dan teruskan', saving: 'Menyimpan…', failed: 'Profil tidak dapat disimpan. Cuba lagi.' },
  plan: { top: 'Rancang perjalanan', title: 'Anda hendak ke mana?', helper: 'Sebut atau taip tempat.', from: 'Dari', to: 'Ke', home: 'Rumah di Bedok', placeholder: 'Masukkan tempat', planning: 'Sedang merancang…', show: 'Tunjukkan perjalanan saya', uncovered: 'Tempat ini belum disokong.', corridor: 'Prototaip ini menyokong:', try: 'Cuba laluan ini' },
  voice: { top: 'Destinasi suara', say: 'Sebut destinasi anda', listening: 'Sedang mendengar…', check: 'Semak destinasi', idle: 'Ketik mikrofon, kemudian bercakap.', requesting: 'Menunggu kebenaran mikrofon…', live: 'Bercakap sekarang.', denied: 'Akses mikrofon dimatikan. Benarkan dalam tetapan pelayar atau taip.', unsupported: 'Input suara tidak tersedia di sini. Taip destinasi anda.', noSpeech: 'Tiada suara didengar. Cuba lagi atau taip.', error: 'Input suara tidak dapat dimulakan. Cuba lagi atau taip.', confirm: 'Adakah ini destinasi yang betul?', heard: 'Saya dengar:', micLive: 'Mikrofon dihidupkan', nothing: 'Belum mendengar apa-apa', privacy: 'Mikrofon bermula hanya selepas anda mengetik dan berhenti selepas selesai.', use: 'Gunakan destinasi ini', tap: 'Ketik untuk bercakap', retry: 'Cuba lagi', type: 'Taip destinasi' },
  overview: { top: 'Perjalanan anda', title: (steps) => `${steps} langkah`, about: (minutes) => `Kira-kira ${minutes} minit mengikut kelajuan berjalan anda.`, stepFree: 'Laluan tanpa tangga', landmarks: 'Panduan mercu tanda', start: 'Mulakan perjalanan', planning: 'Sedang merancang perjalanan…', checking: 'Menyemak keadaan semasa.', empty: 'Belum ada perjalanan', emptyDetail: 'Rancang perjalanan dahulu.', why: 'Mengapa laluan berubah', simulated: 'Gangguan simulasi untuk demonstrasi' },
  stages: { title: 'Demo: satu perjalanan, tiga peristiwa', s1: 'Peringkat 1 · Kesesakan puncak', s2: 'Peringkat 2 · Penutupan terancang', s3: 'Peringkat 3 · Kerosakan tren di hadapan' },
  legs: { modes: { walk: 'Jalan kaki', mrt: 'MRT', bus: 'Bas', taxi: 'Teksi' }, stepFree: { verified: 'Tanpa tangga', unverified: 'Tanpa tangga belum disahkan', not_step_free: 'Ada tangga' }, crowd: { low: 'Kesesakan: rendah', medium: 'Kesesakan: sederhana', high: 'Kesesakan: tinggi' }, illustrative: 'Foto mercu tanda — ilustrasi' },
  sharing: { top: 'Perkongsian perjalanan', title: 'Kongsi perjalanan ini dengan Hui Ling?', idle: 'Hui Ling boleh melihat langkah semasa dan lokasi terakhir sehingga anda tiba.', requesting: 'Menunggu kebenaran lokasi…', denied: 'Akses lokasi dimatikan. Aktifkannya dalam tetapan pelayar dan cuba lagi.', timeout: 'Lokasi anda tidak dapat ditemui. Cuba lagi di tempat dengan isyarat lebih jelas.', service: 'Lokasi tidak dapat dikongsi dengan Hui Ling. Cuba lagi.', unavailable: 'Perkongsian lokasi tidak tersedia dalam pelayar ini.', location: 'Lokasi semasa', locationDetail: 'Dikongsi hanya semasa perjalanan ini', control: 'Anda yang menentukan', controlDetail: 'Perkongsian berhenti apabila perjalanan tamat', request: 'Meminta kebenaran…', retry: 'Cuba lokasi lagi', start: 'Kongsi lokasi dan mula', skip: 'Mula tanpa berkongsi' },
  guide: { step: (step, total) => `Langkah ${step} daripada ${total}`, sharing: 'Berkongsi dengan Hui Ling', saved: 'Menggunakan arah tersimpan', updated: (time) => `Dikemas kini ${time}`, notShared: 'Lokasi tidak dikongsi', playing: 'Sedang dimainkan…', play: 'Mainkan arahan', help: 'Perlukan bantuan?', finish: 'Tamatkan perjalanan', next: 'Langkah seterusnya' },
  help: { top: 'Semak arah anda', checking: 'Menyemak arah anda…', lost: 'Perlukan bantuan mencari jalan?', wrong: 'Berhenti dan berpatah balik', wrongBody: 'Anda sedang menjauhi laluan.', familyTold: 'Hui Ling telah diberitahu.', safe: 'Anda masih berada di laluan yang dirancang.', unavailable: 'Arah tidak dapat disemak. Gunakan butang di bawah.', noJourney: 'Rancang perjalanan dahulu.', correct: 'Tunjukkan arah saya', call: 'Hubungi Hui Ling' },
  taxi: { show: 'Tunjukkan kad ini kepada pemandu', arriveBy: 'Tiba sebelum' },
  alert: { band: 'Amaran perjalanan', happened: { train: 'Tren terhenti di hadapan', flood: 'Banjir kilat di laluan anda', lift: 'Lif tidak beroperasi', weather: 'Hujan lebat di laluan anda', crowd: 'Kesesakan teruk di hadapan', default: 'Keadaan laluan berubah' }, getOff: (p) => `Turun di ${p}`, goTo: (p) => `Pergi ke ${p}`, stay: 'Jangan mulakan perjalanan ini', taxiTo: (d) => `Naik teksi ke ${d}`, cancel: 'Tangguhkan perjalanan', exit: { yes: (r) => `Pintu keluar ${r}: bebas tangga (OSM)`, no: (r) => `Pintu keluar ${r}: OSM tandakan tidak sesuai kerusi roda`, untagged: (r) => `Pintu keluar ${r} (tiada tanda dalam OSM)` }, stand: (n, m) => `Teksi: ${n}, kira-kira ${Math.round(m / 10) * 10} m`, cta: 'Tunjukkan jalan', ok: 'Kembali ke perjalanan', why: 'Mengapa?' },
  arrived: { title: 'Anda telah tiba', detail: 'Perjalanan selesai. Syabas.', again: 'Rancang perjalanan baharu' },
  sos: { top: 'Dapatkan bantuan', title: 'Siapa harus kami hubungi?', idle: 'Tiada panggilan, mesej atau rakaman telah bermula.', family: 'Hui Ling', familyDetail: 'Hantar langkah semasa dan lokasi terakhir', emergency: 'Perkhidmatan kecemasan', emergencyDetail: 'Hubungi 995 untuk bahaya segera', record: 'Rakam mesej audio', recordDetail: 'Pilihan; tidak bermula secara automatik', privacy: 'Audio dan lokasi dikongsi hanya selepas pengesahan.', sendTitle: 'Hantar permintaan bantuan kepada Hui Ling?', sendBody: 'Dia akan menerima langkah semasa dan lokasi terakhir anda. Tiada apa dihantar sebelum pengesahan.', send: 'Hantar permintaan bantuan', emergencyTitle: 'Hubungi perkhidmatan kecemasan?', emergencyBody: 'Hubungi 995 hanya untuk kecemasan segera.' },
}

const ta: UiCopy = {
  back: 'பின்செல்', cancel: 'ரத்துசெய்', language: { welcome: 'வரவேற்கிறோம்!', title: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.', helper: 'இதை பின்னர் மாற்றலாம்.', continue: 'தொடரவும்', aria: 'மொழியைத் தேர்ந்தெடுக்கவும்' },
  profile: { top: 'உங்கள் சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்', title: 'இந்த செயலியைப் பயன்படுத்துவது யார்?', traveller: 'நான் பயணம் செய்கிறேன்', travellerDetail: 'எனது பயணத்தைத் திட்டமிட்டு பின்பற்றுங்கள்.', family: 'நான் குடும்ப உறுப்பினர்', familyDetail: 'என்னுடன் பகிரப்பட்ட பயணங்களைப் பின்பற்றுங்கள்.', consent: 'நீங்கள் தேர்ந்தெடுக்கும்போது மட்டுமே இருப்பிடம் பகிரப்படும்.' },
  setup: { top: 'உங்கள் பயணத் தேவைகள்', title: 'உங்களுக்கு ஏற்ற பாதைக்காக சில கேள்விகள்', shelter: 'மூடிய பாதைகளை விரும்புகிறீர்களா?', shelterYes: 'ஆம், மூடிய பாதை', shelterNo: 'விருப்பம் இல்லை', stairs: 'படிக்கட்டுகளைப் பயன்படுத்த முடியுமா?', stairsAvoid: 'படிக்கட்டுகளைத் தவிர்க்கிறேன்', stairsOk: 'படிக்கட்டு பரவாயில்லை', wheelchair: 'சக்கர நாற்காலி பயன்படுத்துகிறீர்களா?', wcYes: 'ஆம்', wcNo: 'இல்லை', pace: 'எப்படி நடக்கிறீர்கள்?', paceSlow: 'மெதுவாக நடப்பேன்', paceAvg: 'சராசரி வேகத்தில் நடப்பேன்', walk: 'எவ்வளவு தூரம் வசதியாக நடக்க முடியும்?', metres: (m) => `${m} மீ`, save: 'சேமித்து தொடரவும்', saving: 'சேமிக்கிறது…', failed: 'சுயவிவரத்தைச் சேமிக்க முடியவில்லை. மீண்டும் முயலவும்.' },
  plan: { top: 'பயணத்தைத் திட்டமிடுங்கள்', title: 'நீங்கள் எங்கு செல்கிறீர்கள்?', helper: 'இடத்தைச் சொல்லுங்கள் அல்லது தட்டச்சு செய்யுங்கள்.', from: 'இருந்து', to: 'செல்லும் இடம்', home: 'Bedok வீடு', placeholder: 'இடத்தை உள்ளிடவும்', planning: 'திட்டமிடுகிறது…', show: 'எனது பயணத்தைக் காட்டு', uncovered: 'இந்த இடம் இன்னும் ஆதரிக்கப்படவில்லை.', corridor: 'இந்த மாதிரி ஆதரிப்பது:', try: 'இந்தப் பாதையை முயற்சிக்கவும்' },
  voice: { top: 'குரல் இலக்கு', say: 'உங்கள் இலக்கைச் சொல்லுங்கள்', listening: 'கேட்கிறது…', check: 'இலக்கைச் சரிபார்க்கவும்', idle: 'மைக்ரோஃபோனைத் தட்டி பேசுங்கள்.', requesting: 'மைக்ரோஃபோன் அனுமதிக்காக காத்திருக்கிறது…', live: 'இப்போது பேசுங்கள்.', denied: 'மைக்ரோஃபோன் அணைக்கப்பட்டுள்ளது. உலாவி அமைப்பில் அனுமதிக்கவும் அல்லது தட்டச்சு செய்யவும்.', unsupported: 'இங்கே குரல் உள்ளீடு கிடைக்கவில்லை. இலக்கைத் தட்டச்சு செய்யவும்.', noSpeech: 'எதுவும் கேட்கவில்லை. மீண்டும் முயலவும் அல்லது தட்டச்சு செய்யவும்.', error: 'குரல் உள்ளீட்டைத் தொடங்க முடியவில்லை. மீண்டும் முயலவும் அல்லது தட்டச்சு செய்யவும்.', confirm: 'இது சரியான இலக்கா?', heard: 'நான் கேட்டது:', micLive: 'மைக்ரோஃபோன் இயங்குகிறது', nothing: 'இன்னும் எதுவும் கேட்கவில்லை', privacy: 'நீங்கள் தட்டிய பிறகே மைக்ரோஃபோன் தொடங்கி, கேட்பது முடிந்ததும் நிற்கும்.', use: 'இந்த இலக்கைப் பயன்படுத்தவும்', tap: 'பேச தட்டவும்', retry: 'மீண்டும் முயலவும்', type: 'இலக்கைத் தட்டச்சு செய்யவும்' },
  overview: { top: 'உங்கள் பயணம்', title: (steps) => `${steps} படிகள்`, about: (minutes) => `உங்கள் நடை வேகத்தில் சுமார் ${minutes} நிமிடங்கள்.`, stepFree: 'படிக்கட்டு இல்லா பாதை', landmarks: 'அடையாள வழிகாட்டல்', start: 'பயணத்தைத் தொடங்கவும்', planning: 'பயணத்தைத் திட்டமிடுகிறது…', checking: 'தற்போதைய நிலையைச் சரிபார்க்கிறது.', empty: 'இன்னும் பயணம் இல்லை', emptyDetail: 'முதலில் ஒரு பயணத்தைத் திட்டமிடுங்கள்.', why: 'பாதை ஏன் மாறியது', simulated: 'விளக்கத்திற்கான உருவகப்படுத்தப்பட்ட தடங்கல்' },
  stages: { title: 'டெமோ: ஒரு பயணம், மூன்று நிகழ்வுகள்', s1: 'கட்டம் 1 · உச்ச நேரக் கூட்டம்', s2: 'கட்டம் 2 · திட்டமிட்ட மூடல்', s3: 'கட்டம் 3 · முன்னால் ரயில் கோளாறு' },
  legs: { modes: { walk: 'நடை', mrt: 'MRT', bus: 'பேருந்து', taxi: 'டாக்சி' }, stepFree: { verified: 'படிக்கட்டு இல்லை', unverified: 'படிக்கட்டு நிலை உறுதி செய்யப்படவில்லை', not_step_free: 'படிக்கட்டு உள்ளது' }, crowd: { low: 'கூட்டம்: குறைவு', medium: 'கூட்டம்: நடுத்தரம்', high: 'கூட்டம்: அதிகம்' }, illustrative: 'அடையாளப் புகைப்படம் — விளக்கத்திற்காக' },
  sharing: { top: 'பயணப் பகிர்வு', title: 'இந்தப் பயணத்தை Hui Ling-உடன் பகிரவா?', idle: 'நீங்கள் சேரும்வரை தற்போதைய படியையும் கடைசி இருப்பிடத்தையும் Hui Ling பார்க்கலாம்.', requesting: 'இருப்பிட அனுமதிக்காக காத்திருக்கிறது…', denied: 'இருப்பிட அணுகல் அணைக்கப்பட்டுள்ளது. உலாவி அமைப்பில் இயக்கி மீண்டும் முயலவும்.', timeout: 'உங்கள் இருப்பிடத்தைக் கண்டறிய முடியவில்லை. நல்ல சிக்னல் உள்ள இடத்தில் முயலவும்.', service: 'Hui Ling-உடன் இருப்பிடத்தைப் பகிர முடியவில்லை. மீண்டும் முயலவும்.', unavailable: 'இந்த உலாவியில் இருப்பிடப் பகிர்வு கிடைக்கவில்லை.', location: 'தற்போதைய இருப்பிடம்', locationDetail: 'இந்தப் பயணத்தில் மட்டும் பகிரப்படும்', control: 'கட்டுப்பாடு உங்களிடம்', controlDetail: 'பயணம் முடிந்ததும் பகிர்வு நிற்கும்', request: 'அனுமதி கேட்கிறது…', retry: 'இருப்பிடத்தை மீண்டும் முயலவும்', start: 'இருப்பிடத்தைப் பகிர்ந்து தொடங்கவும்', skip: 'பகிராமல் தொடங்கவும்' },
  guide: { step: (step, total) => `படி ${step} / ${total}`, sharing: 'Hui Ling-உடன் பகிர்கிறது', saved: 'சேமித்த வழிகளைப் பயன்படுத்துகிறது', updated: (time) => `${time} புதுப்பிக்கப்பட்டது`, notShared: 'இருப்பிடம் பகிரப்படவில்லை', playing: 'ஒலிக்கிறது…', play: 'வழிகாட்டலைக் கேட்க', help: 'உதவி வேண்டுமா?', finish: 'பயணத்தை முடிக்கவும்', next: 'அடுத்த படி' },
  help: { top: 'உங்கள் திசையைச் சரிபார்க்கவும்', checking: 'உங்கள் திசையைச் சரிபார்க்கிறது…', lost: 'வழியைக் கண்டறிய உதவி வேண்டுமா?', wrong: 'நிறுத்தி திரும்புங்கள்', wrongBody: 'நீங்கள் பாதையிலிருந்து விலகிச் செல்கிறீர்கள்.', familyTold: 'Hui Ling-க்கு தெரிவிக்கப்பட்டது.', safe: 'நீங்கள் இன்னும் திட்டமிட்ட பாதையில் உள்ளீர்கள்.', unavailable: 'திசையைச் சரிபார்க்க முடியவில்லை. கீழே உள்ள பொத்தான்களைப் பயன்படுத்தவும்.', noJourney: 'முதலில் பயணத்தைத் திட்டமிடுங்கள்.', correct: 'என் திசையைக் காட்டு', call: 'Hui Ling-ஐ தொடர்புகொள்ளவும்' },
  taxi: { show: 'இந்த அட்டையை ஓட்டுநரிடம் காட்டுங்கள்', arriveBy: 'சேர வேண்டிய நேரம்' },
  alert: { band: 'பயண எச்சரிக்கை', happened: { train: 'முன்னால் ரயில் நின்றுவிட்டது', flood: 'பாதையில் திடீர் வெள்ளம்', lift: 'மின்தூக்கி செயலிழந்துள்ளது', weather: 'பாதையில் கனமழை', crowd: 'முன்னால் கடும் நெரிசல்', default: 'பாதை நிலை மாறியுள்ளது' }, getOff: (p) => `${p}இல் இறங்குங்கள்`, goTo: (p) => `${p}க்குச் செல்லுங்கள்`, stay: 'இந்தப் பயணத்தைத் தொடங்க வேண்டாம்', taxiTo: (d) => `${d}க்கு டாக்சியில் செல்லுங்கள்`, cancel: 'வேறு நாள் பயணியுங்கள்', exit: { yes: (r) => `வெளியேறும் வழி ${r}: படிக்கட்டு இல்லை (OSM)`, no: (r) => `வெளியேறும் வழி ${r}: சக்கர நாற்காலிக்கு ஏற்றதல்ல என OSM குறித்துள்ளது`, untagged: (r) => `வெளியேறும் வழி ${r} (OSM இல் குறிக்கப்படவில்லை)` }, stand: (n, m) => `டாக்சி நிலையம்: ${n}, சுமார் ${Math.round(m / 10) * 10} மீ`, cta: 'வழியைக் காட்டு', ok: 'பயணத்திற்குத் திரும்பு', why: 'ஏன்?' },
  arrived: { title: 'வந்து சேர்ந்துவிட்டீர்கள்', detail: 'பயணம் நிறைவடைந்தது. நன்று.', again: 'புதிய பயணத்தைத் திட்டமிடுங்கள்' },
  sos: { top: 'உதவி பெறுங்கள்', title: 'யாரைத் தொடர்புகொள்ள வேண்டும்?', idle: 'அழைப்பு, செய்தி அல்லது பதிவு எதுவும் தொடங்கவில்லை.', family: 'Hui Ling', familyDetail: 'தற்போதைய படி மற்றும் கடைசி இருப்பிடத்தை அனுப்பவும்', emergency: 'அவசர சேவைகள்', emergencyDetail: 'உடனடி ஆபத்திற்கு 995-ஐ அழைக்கவும்', record: 'ஒலி செய்தியைப் பதிவு செய்யவும்', recordDetail: 'விருப்பமானது; தானாக தொடங்காது', privacy: 'உறுதிப்படுத்திய பிறகே ஒலி மற்றும் இருப்பிடம் பகிரப்படும்.', sendTitle: 'Hui Ling-க்கு உதவி கோரிக்கையை அனுப்பவா?', sendBody: 'உங்கள் தற்போதைய படியும் கடைசி இருப்பிடமும் அனுப்பப்படும். உறுதிப்படுத்தும் வரை எதுவும் அனுப்பப்படாது.', send: 'உதவி கோரிக்கையை அனுப்பவும்', emergencyTitle: 'அவசர சேவைகளை அழைக்கவா?', emergencyBody: 'உடனடி அவசரத்திற்கு மட்டும் 995-ஐ அழைக்கவும்.' },
}

export const uiCopy: Record<Locale, UiCopy> = { en, zh, ms, ta }
